pipeline {
    agent any
    tools {
        maven 'maven-jenkins' 
    }
    stages {
        stage('Intialize') {
            steps {
                sh 'mvn --version'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean -DskipTests  package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage("Run") {
           steps{
           sh 'mvn spring-boot:run -Dserver.port=8989 &'
           }
        }
    }
}