pipeline {
    agent any
    tools {
        maven 'maven-jenkins' 
    }
    stages {
        stage('Intialize') {
            steps {
                sh 'mvn --version'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean -DskipTests  package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('CreateJar') {
            steps {
                sh 'java -jar spring-boot-user-api-0.0.1-SNAPSHOT.jar'
            }
        }
    }
}